config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Static
  root 'static#home'

  # Sessions
  get '/login' => 'session#new'
  post '/login' => 'session#create' 
  post '/logout' => 'session#destroy'

  get '/auth/facebook/callback' => "session#create_with_fb"

  # Models
   get '/signup' => 'users#new'
  
   resources :users, except: [:index] do
    resources :accounts
  end

  resources :accounts do
    resources :digitalprints, only: [:new, :create]
  end

end

app/models/account.rb
class Account < ApplicationRecord
    has_many :digitalprints	
    has_many :users, through: :digitalprints

    validates_presence_of :org_name, :website, :toll_free_number
    validates_uniqueness_of :org_name

    accepts_nested_attributes_for :digitalprints

    scope :org_name_search, -> (search) { where("org_name >= ?", search) }

    def self.find_or_create_account(params)
        account = Account.find_by(org_name: params[:org_name])
        if !!account
            account.digitalprints_attributes= params[:digitalprints_attributes]
            account.save
            account
        else
            Account.create(params)
        end
    end

    def self.email_accounts
        includes(:digitalprints).where(digitalprints: { kind: 'Email' })
    end

    def self.email_count
        email_accounts.count
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/digitalprint.rb
class Digitalprint < ApplicationRecord
    belongs_to :user
    belongs_to :account

    validates_uniqueness_of :kind

    # validates :kind, uniqueness: { scope: :user,
    # message: "update"}

    accepts_nested_attributes_for :account

    # def account_name=(org_name)
    #     self.account = Account.find_or_create_by(org_name: org_name)
    # end

    # def account_name
    #     self.account ? self.account.org_name : nil
    # end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :digitalprints	
    has_many :accounts, through: :digitalprints
    validates_presence_of :email
    validates_uniqueness_of :email
    has_secure_password


    def full_name
        first_name + " " + last_name unless first_name.nil? || last_name.nil?
    end

    def self.google_users
        includes(:accounts).where(accounts: { org_name: 'Google' })
    end

    def self.total_users
        self.count
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :confirm_logged_in
    before_action :set_account, except: [:new, :create, :index]

    def index
        @accounts = User.find_by(id: session[:user_id]).accounts.distinct
        if params[:search]
            @accounts = @accounts.org_name_search(params[:search])
        end
    end

    def new
        @account = Account.new
        @account.digitalprints.build(user_id: session[:user_id])
    end

    def create
        byebug
        @account = Account.find_or_create_account(account_params)
        if @account.save
            redirect_to account_path(@account)
        else
            @messages = @account.errors.full_messages
            render 'new'
        end
    end

    def show

    end

    def edit

    end

    def update
        if @account.update(account_params)
            redirect_to account_path(@account)
        else
            @messages = @account.errors.full_messages
            render 'edit'
        end
    end

    def destroy
        @account.delete
        redirect_to accounts_path
    end

    private

    def set_account
        @account = Account.find_by(id: params[:id])
    end

    def account_params
        params.require(:account).permit(
            :org_name, 
            :website, 
            :toll_free_number,
            digitalprints_attributes: [:kind, :id, :user_id] 
        )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user

    def current_user
        User.find_by(id: session[:user_id])
    end

    def confirm_logged_in
        redirect_to root_path if !current_user
    end

    def redirect_if_logged_in
        redirect_to accounts_path if current_user
    end

end

app/controllers/digitalprints_controller.rb
class DigitalprintsController < ApplicationController
    before_action :confirm_logged_in

    def new
        if params[:account_id]
            @account = Account.find_by(id: params[:account_id])
            @digitalprint = @account.digitalprints.build
        else
            @digitalprint = Digitalprint.new
            @digitalprint.build_account
        end
    end

    def create
        d = Digitalprint.new(digitalprint_params)
        d.user = current_user
        d.account_id = params[:account_id]
        d.save
        redirect_to account_path(d.account)
    end

    private

    def digitalprint_params
        params.require(:digitalprint).permit(:kind, account_attributes: [:id, :org_name, :website, :toll_free_number])
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    before_action :redirect_if_logged_in, except: [:destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to accounts_path
        else
            @messages = ["Username or password incorrect"]
            render 'new'
        end
    end

    def create_with_fb
        @user = User.find_or_create_by(email: auth['email']) do |u|
            u.password = 'password' #update to random password generator before production
        end
        @user.save
        session[:user_id] = @user.id
    
        redirect_to accounts_path
    end


    def destroy
        session.delete("user_id")
        redirect_to root_path
    end

    private

    def auth
      request.env['omniauth.auth']["info"]
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new]
    before_action :set_user, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to accounts_path
        else
            @messages = @user.errors.full_messages
            render 'new'
        end
    end

    def show

    end

    def edit

    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end

    def destroy
        @user.delete
        redirect_to root_path
    end

    private

    def set_user
        @user = User.find_by(id: params[:id])
    end

    def user_params
        params.require(:user).permit(
            :first_name, 
            :last_name, 
            :email, 
            :mobile_number, 
            :password, 
            :password_confirmation
        )
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/digitalprints_helper.rb
module DigitalprintsHelper

    def form_url_helper(account)
        account ? account_digitalprints_path(account) : digitalprints_path
    end

    def digitalprint_options
        ["Email", "Credit Card", "Phone Number","SSN", "Social Media User", "Biometric", "Birthdate", "Employment Details"]
    end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<h3 class="h3 text-center user-heading"> <%= type_form %> </h3>

<%= form_for @account, html: {class: "main-form"} do |f| %>
    
    <div class="form-group">
        <%= f.text_field :org_name, list: "org_names_autocomplete", placeholder: "Organization", class: "form-control" %>
            <datalist id="org_names_autocomplete">
                <% Account.all.each do |account| %>
                <option value= <%= "#{account.org_name}" %>>
                <% end %>
            </datalist>
    </div>

    <div class="form-group">   
        <%= f.text_field :website, class: "form-control", placeholder: "Website to submit data info requests" %>
    </div>

    <div class="form-group">   
        <%= f.text_field :toll_free_number, class: "form-control", placeholder: "Toll free number for data info requests" %>
    </div>

    <div class="form-group">
      <p class="account-question"> What type of information is associated with your account?  </p>
        <%= f.fields_for :digitalprints do |d| %>
          <div class="form-group">
            <%= d.select :kind, digitalprint_options, {} , class: "form-control" %>
          </div>
            <%= d.hidden_field :user_id %>
        <% end %>
    </div>

    <div class="text-center"> 
        <%= f.submit class:"btn btn-primary" %>
    </div>

<% end %>

app/views/accounts/edit.html.erb
<%=render partial: "application/messages", locals: {messages: @messages || [] } %>

<%= render partial: 'form', locals: {type_form: "Edit Account Info"} %>

app/views/accounts/index.html.erb
<div class="search-form">
    <%=form_tag accounts_path, method: :get, class: "main-form" do %>
        <div class="form-group"> 
            <%=text_field_tag :search, "Search for Organization", class: "form-control" %>
        </div>
        <div class="text-center"> 
            <%=submit_tag :search, class:"btn btn-primary" %>
        </div>
    <%end%>
</div>

<% if @accounts == [] %>

    <h5 class="h5 text-center empty-index"> You have not loaded any digitalprints. Get started <%= link_to "here", new_account_path %>! </h5>

<% else %>
    <h5 class="h5 text-center empty-index"> Add new account <%= link_to "here", new_account_path %>! </h5>

    <% @accounts.each do |account| %>

        <div class="card-container text-center">   
            <div class="card text-center">
                <div class="card-body">
                    <%= link_to account.org_name, account_path(account), class:"btn btn-primary btn-sm btn-block"  %>
                    <hr class="light">
                    <p class="card-text"> Digitalprints </p>
                        <% account.digitalprints.each do |d| %>
                            <li> <%= d.kind %> </li>
                        <% end%>
                </div>
                <div class="card-footer">
                    <%= link_to "Add digitalprint", new_account_digitalprint_path(account), class:"btn btn-secondary btn-sm btn-block"  %>
                </div>
            </div>
        </div> 

    <% end %>
<% end %>

app/views/accounts/new.html.erb
<%=render partial: "application/messages", locals: {messages: @messages || [] } %>

<%= render partial: 'form', locals: {type_form: "New Account Info"} %>

app/views/accounts/show.html.erb
<%=render partial: "application/messages", locals: {messages: @messages || [] } %>

<div class="container-fluid padding main-user-show">
    <div class="row text-center">
        <div class="col">
            <h5> Account Information </h5>
            <hr class="light">
            <p> Organization: <br>
                <%= @account.org_name %> </p>
            <p> Website to submit data info requests: <br>
                <%= @account.website %> </p>
            <p> Toll free number for data info requests: <br>
                <%= @account.toll_free_number %> </p>
        
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch1">
                    <label class="custom-control-label" for="customSwitch1"> Right to Know </label>
                </div>
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch2">
                    <label class="custom-control-label" for="customSwitch2"> Right to Delete </label>
                </div>
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch3">
                    <label class="custom-control-label" for="customSwitch3"> Right to Opt Out</label>
                </div>
                <br>
            
            <hr class="light">
            <h5> Associated Digitalprints </h5>
            <% @account.digitalprints.each do|d| %>
                <li> <%= d.kind %> </li>
            <% end%>
        
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-4">
            <%= button_to 'Edit Account', edit_account_path(@account), method: :get, class:"btn btn-outline-light" %>
        </div>
        <div class="col-md-4"> 
            <%= button_to 'Add Digitalprint', new_account_digitalprint_path(@account), method: :get, class:"btn btn-outline-light" %>
        </div>
        <div class="col-md-4"> 
            <%= button_to 'Delete Account', account_path(@account), method: :delete, class:"btn btn-primary" %> 
        </div>
    </div>
</div>

<h5 class="h5 text-center empty-index"> Add new account <%= link_to "here", new_account_path %>! </h5>

app/views/application/_messages.html.erb
<% messages.each do |m| %>
  <div class="alert alert-danger text-center"" role="alert">
    <%= m %>
  </div>
<% end %>

app/views/digitalprints/_form.html.erb
<h3 class="h3 text-center user-heading"> <%= type_form %> </h3>

<%= form_for @digitalprint, url: form_url_helper(@account), html: {class: "main-form"} do |f| %>
  
  <!-- <%= f.hidden_field :user_id %> -->

  <div class="form-group">
    <p class="account-question"> What type of information is associated with your account?  </p>
        <%= f.select :kind, digitalprint_options, {} , class: "form-control" %>
  </div>

  <% if @account %>
    <div class="form-group">
      <label class= "form-control"> <%= @account.org_name  %> </label>
    </div>

  <% else %>

    <div class="form-group">
        <p class="account-question"> What account is associated with this digitalprint?  </p>
        <%= f.fields_for :account do |a| %>
        
          <!-- <div class="form-group"></div>
            <%= a.collection_select :org_name, Account.all, :org_name, :org_name, {}, class: "form-control" %>
          </div> -->

          <div class="form-group">
            <%= a.text_field :org_name, list: "org_names_autocomplete", placeholder: "Organization", class: "form-control" %>
                <datalist id="org_names_autocomplete">
                    <% Account.all.each do |account| %>
                    <option value= <%= "#{account.org_name}" %>
                    <% end %>
                </datalist>
          </div>

          <div class="form-group"> 
            <%= a.text_field :website, class: "form-control", placeholder: "Website to submit data info requests" %>
          </div>

          <div class="form-group">   
            <%= a.text_field :toll_free_number, class: "form-control", placeholder: "Toll free number for data info requests" %>
          </div>

        <% end %>
    </div>
  <% end %>

  <div class="text-center"> 
    <%= f.submit class:"btn btn-primary" %>
  </div   

<% end %>

app/views/digitalprints/new.html.erb
<%=render partial: "application/messages", locals: {messages: @messages || [] } %>

<%= render partial: 'form', locals: {type_form: "New Digitalprint"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppDataPreferenceRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <%= image_tag "valubl_logo4.png", size: "180x40"%></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
          <span class="navbar-toggler-icon"> </span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if !current_user %>
              <li class="nav-item">
                <%= link_to "SIGN UP", signup_path, class: "nav-link" %> </li>
              <li class="nav-item" >
                <%= link_to "LOGIN", login_path, class: "nav-link" %> </li>
            <% else %>
              <li class="nav-item" >
                <%= link_to "DIGITALPRINT ACCOUNTS", user_accounts_path(current_user), class: "nav-link" %> </li>
                <li class="nav-item" >
                  <%= link_to "MY ACCOUNT", user_path(current_user), class: "nav-link" %> </li>
              <li class="nav-item" >
                <%= link_to "LOGOUT", logout_path, method: :post, class: "nav-link" %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <!-- <footer class="footer sticky-bottom">

      <div class="container-fluid padding">
        <div class="row text-center">
          <div class="col-12">
            <hr class="light-100">
            <h7> Created with by Jon Chasse </h7>
          </div>
        </div>
      </div>

    </footer> -->

  </body>
</html>

app/views/session/new.html.erb
<%=render partial: "application/messages", locals: {messages: @messages || [] } %>

<h3 class="h3 text-center user-heading"> Login </h3>

<!-- <form action="" class="main-form needs-validation" novalidate> -->
<%= form_tag login_path, method: :post, class: "main-form" do %>
    <div class="form-group">   
        <%= text_field_tag :email, "Email", class: "form-control" %>
    </div>
    <div class="form-group">   
        <%= password_field_tag :password, "", placeholder: "Password", class: "form-control" %>
    </div>
    <div class="form-group text-center">
        <%= submit_tag "Log In", class:"btn btn-primary" %>
    </div>

    <div class="row text-center">
        <div class="col-md-12">
            <%= link_to('Log in with Facebook!', '/auth/facebook') %>
        </div>
        <div class="col-md-6"> 
        </div>
    </div>

<% end %>

app/views/users/_form.html.erb
<h3 class="h3 text-center user-heading"> <%= type_form %> </h3>

<%= form_for @user, html: {class: "main-form"} do |f| %>
    <div class="form-group">
        <div class="row">
            <div class="col">
                <%= f.text_field :first_name, class: "form-control", placeholder: "First name" %>
            </div>
            <div class="col">
                <%= f.text_field :last_name, class: "form-control", placeholder: "Last name" %>
            </div>
        </div>
    </div>
    <div class="form-group">   
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
    <div class="form-group">   
        <%= f.telephone_field :mobile_number, class: "form-control", placeholder: "Mobile Phone Number" %>
    </div>
    <div class="form-group">   
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
    <div class="form-group">   
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
    </div>
    <div class="text-center"> 
        <%= f.submit class: "btn btn-primary" %>
    </div

<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form', locals: {type_form: "Edit User Info"} %>

app/views/users/new.html.erb
<%=render partial: "application/messages", locals: {messages: @messages || [] } %>

<%= render partial: 'form', locals: {type_form: "Create New User"} %> 

app/views/users/show.html.erb
<div class="container-fluid padding main-user-show">
    <div class="row text-center">
        <div class="col">
            <h5> User Information </h5>
            <hr class="light">
            <p> <%= @user.full_name %> </p>
            <p> <%= @user.email %> </p>
            <p> <%= @user.mobile_number %> </p>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-6">
            <%= button_to 'Edit User', edit_user_path(@user), method: :get, class:"btn btn-outline-light" %>
        </div>
        <div class="col-md-6"> 
            <%= button_to 'Delete User', user_path(@user), method: :delete, class:"btn btn-primary" %> 
        </div>
    </div>
</div>